/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panizio.view;
import java.awt.event.KeyEvent;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import panizio.dao.TabelasDAO;
import panizio.utils.ManipularCampos;
/**
 *
 * @author lucas Panizio
 */
public class FormOcorrencia extends javax.swing.JFrame {
    private static TabelasDAO tblDAO = new TabelasDAO();
    
    
    /**
     * Creates new form FormOcorrencia
     */
    public FormOcorrencia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel1 = new javax.swing.JPanel();
        btnPesquisarOc = new javax.swing.JButton();
        txtPesquisarOcorrencia = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblOcorrencias = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        cmbOcorrencias = new javax.swing.JComboBox<>();
        lblOcorrencias = new javax.swing.JLabel();
        lblDataReceb = new javax.swing.JLabel();
        txtDataReceb = new javax.swing.JFormattedTextField();
        lblNomeReceb = new javax.swing.JLabel();
        txtNomeReceb = new javax.swing.JTextField();
        btnSalvarOc = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtDescricaoOc = new javax.swing.JTextArea();
        lblCodOcorrencia = new javax.swing.JLabel();
        txtCodOcorrencia = new javax.swing.JTextField();
        btnIncluirOc = new javax.swing.JButton();
        lblCodMinuta = new javax.swing.JLabel();
        txtCodMinuta = new javax.swing.JTextField();
        btnCancelarOc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ocorrências");
        setResizable(false);

        JPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnPesquisarOc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panizio/imagens/zoom 20x20.png"))); // NOI18N
        btnPesquisarOc.setText("PESQUISAR");
        btnPesquisarOc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarOcActionPerformed(evt);
            }
        });
        btnPesquisarOc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPesquisarOcKeyPressed(evt);
            }
        });

        txtPesquisarOcorrencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisarOcorrenciaKeyPressed(evt);
            }
        });

        jLabel2.setText("Digite o número da Minuta para pesquisar suas ocorrências");

        javax.swing.GroupLayout JPanel1Layout = new javax.swing.GroupLayout(JPanel1);
        JPanel1.setLayout(JPanel1Layout);
        JPanel1Layout.setHorizontalGroup(
            JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel1Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(JPanel1Layout.createSequentialGroup()
                        .addComponent(txtPesquisarOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPesquisarOc))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPanel1Layout.setVerticalGroup(
            JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPesquisarOc)
                    .addComponent(txtPesquisarOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tblOcorrencias.setAutoCreateRowSorter(true);
        tblOcorrencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Emissão Minuta", "Nota Fiscal", "Ocorrência", "Data Oc.", "Usuário"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblOcorrencias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblOcorrenciasMouseReleased(evt);
            }
        });
        tblOcorrencias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblOcorrenciasKeyPressed(evt);
            }
        });
        jScrollPane4.setViewportView(tblOcorrencias);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cmbOcorrencias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "1 - ENTREGA REALIZADA", "2 - AVARIA", "3 - CLIENTE AUSENTE", "4 - RECUSA", "5 - DEVOLUÇÃO", "6 - EXTRAVIO", "7 - OCORRENCIA FECHADA", "8 - FALTA DE TEMPO", "9 - OUTRAS OCORRENCIAS" }));
        cmbOcorrencias.setEnabled(false);
        cmbOcorrencias.setMinimumSize(new java.awt.Dimension(50, 24));
        cmbOcorrencias.setPreferredSize(new java.awt.Dimension(50, 24));

        lblOcorrencias.setText("Ocorrências");

        lblDataReceb.setText("Data do Recebimento");

        try {
            txtDataReceb.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataReceb.setEnabled(false);
        txtDataReceb.setMinimumSize(new java.awt.Dimension(14, 24));
        txtDataReceb.setPreferredSize(new java.awt.Dimension(14, 24));

        lblNomeReceb.setText("Nome do Recebedor");

        txtNomeReceb.setEnabled(false);

        btnSalvarOc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panizio/imagens/check 22x22.png"))); // NOI18N
        btnSalvarOc.setText("SALVAR");
        btnSalvarOc.setEnabled(false);
        btnSalvarOc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarOcActionPerformed(evt);
            }
        });
        btnSalvarOc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSalvarOcKeyPressed(evt);
            }
        });

        txtDescricaoOc.setColumns(20);
        txtDescricaoOc.setRows(5);
        txtDescricaoOc.setBorder(javax.swing.BorderFactory.createTitledBorder("Descrição"));
        txtDescricaoOc.setEnabled(false);
        txtDescricaoOc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDescricaoOcKeyPressed(evt);
            }
        });
        jScrollPane6.setViewportView(txtDescricaoOc);

        lblCodOcorrencia.setText("Cód. Ocorrência");

        txtCodOcorrencia.setEnabled(false);

        btnIncluirOc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panizio/imagens/add 27x27.png"))); // NOI18N
        btnIncluirOc.setText("INCLUIR");
        btnIncluirOc.setEnabled(false);
        btnIncluirOc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirOcActionPerformed(evt);
            }
        });

        lblCodMinuta.setText("Cod. Minuta");

        txtCodMinuta.setEnabled(false);

        btnCancelarOc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panizio/imagens/cancel 22x22 (2).png"))); // NOI18N
        btnCancelarOc.setText("CANCELAR");
        btnCancelarOc.setEnabled(false);
        btnCancelarOc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarOcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtNomeReceb, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(lblCodOcorrencia, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCodOcorrencia, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                                        .addGap(20, 20, 20)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblOcorrencias)
                                            .addComponent(cmbOcorrencias, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblCodMinuta)
                                            .addComponent(txtCodMinuta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblDataReceb)
                                            .addComponent(txtDataReceb, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(lblNomeReceb))
                                .addGap(20, 20, 20)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnIncluirOc, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelarOc, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSalvarOc, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIncluirOc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSalvarOc)
                        .addComponent(btnCancelarOc)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lblCodMinuta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodMinuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lblDataReceb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDataReceb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lblCodOcorrencia)
                                .addGap(4, 4, 4)
                                .addComponent(txtCodOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lblOcorrencias)
                                .addGap(4, 4, 4)
                                .addComponent(cmbOcorrencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(lblNomeReceb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeReceb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane6))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4)
                    .addComponent(jSeparator3)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(JPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarOcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarOcActionPerformed
        if (!txtPesquisarOcorrencia.getText().isEmpty()) {
            int id_minuta = Integer.parseInt(txtPesquisarOcorrencia.getText());
            tblDAO.atualizarTblOcorrencias((DefaultTableModel) tblOcorrencias.getModel(), id_minuta);

            if (tblOcorrencias.getModel().getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "A minuta pesquisada não foi emitida " + '\n' + ""
                    + "ou não possui ocorrências.", "INFORMAÇÃO", JOptionPane.INFORMATION_MESSAGE);
                txtPesquisarOcorrencia.requestFocus();
            } else {
                btnIncluirOc.setEnabled(true);
            }
        }
    }//GEN-LAST:event_btnPesquisarOcActionPerformed

    private void btnPesquisarOcKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnPesquisarOcKeyPressed
        btnPesquisarOc.doClick();
    }//GEN-LAST:event_btnPesquisarOcKeyPressed

    private void txtPesquisarOcorrenciaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarOcorrenciaKeyPressed
        if (txtPesquisarOcorrencia.getText().length() == 1) {
            ((DefaultTableModel) tblOcorrencias.getModel()).setRowCount(0);
            btnIncluirOc.setEnabled(false);
        }
    }//GEN-LAST:event_txtPesquisarOcorrenciaKeyPressed

    private void tblOcorrenciasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOcorrenciasMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tblOcorrenciasMouseReleased

    private void tblOcorrenciasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblOcorrenciasKeyPressed

    }//GEN-LAST:event_tblOcorrenciasKeyPressed

    private void btnSalvarOcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarOcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarOcActionPerformed

    private void btnSalvarOcKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSalvarOcKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnSalvarOc.doClick();
        }
    }//GEN-LAST:event_btnSalvarOcKeyPressed

    private void txtDescricaoOcKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescricaoOcKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_TAB) {
            btnSalvarOc.requestFocus();
        }
    }//GEN-LAST:event_txtDescricaoOcKeyPressed

    private void btnIncluirOcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirOcActionPerformed
        ManipularCampos.habilitar_desabilitar(Arrays.asList(txtCodMinuta, txtCodOcorrencia, txtDescricaoOc,
            cmbOcorrencias, txtNomeReceb, txtDataReceb,btnSalvarOc,btnCancelarOc), true);
    btnIncluirOc.setEnabled(false);
    txtCodMinuta.requestFocus();
    }//GEN-LAST:event_btnIncluirOcActionPerformed

    private void btnCancelarOcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarOcActionPerformed
        btnIncluirOc.setEnabled(true);
        ManipularCampos.limparCampos(Arrays.asList(txtCodOcorrencia, txtCodMinuta, txtDescricaoOc, txtDataReceb, txtNomeReceb));
        cmbOcorrencias.setSelectedIndex(0);
        ManipularCampos.habilitar_desabilitar(Arrays.asList(btnCancelarOc, btnSalvarOc, txtCodOcorrencia,
            txtDataReceb, txtNomeReceb, txtDescricaoOc, cmbOcorrencias, txtCodMinuta), false);
    }//GEN-LAST:event_btnCancelarOcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormOcorrencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormOcorrencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormOcorrencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormOcorrencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormOcorrencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel1;
    private javax.swing.JButton btnCancelarOc;
    private javax.swing.JButton btnIncluirOc;
    private javax.swing.JButton btnPesquisarOc;
    private javax.swing.JButton btnSalvarOc;
    private javax.swing.JComboBox<String> cmbOcorrencias;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblCodMinuta;
    private javax.swing.JLabel lblCodOcorrencia;
    private javax.swing.JLabel lblDataReceb;
    private javax.swing.JLabel lblNomeReceb;
    private javax.swing.JLabel lblOcorrencias;
    private javax.swing.JTable tblOcorrencias;
    private javax.swing.JTextField txtCodMinuta;
    private javax.swing.JTextField txtCodOcorrencia;
    private javax.swing.JFormattedTextField txtDataReceb;
    private javax.swing.JTextArea txtDescricaoOc;
    private javax.swing.JTextField txtNomeReceb;
    private javax.swing.JTextField txtPesquisarOcorrencia;
    // End of variables declaration//GEN-END:variables
}
