/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panizio.view;

import java.awt.Component;
import java.awt.event.KeyEvent;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import panizio.dao.MinutaDAO;
import panizio.dao.OcorrenciaDAO;
import panizio.dao.TabelasDAO;
import panizio.model.Ocorrencia;
import panizio.utils.AtributosGlobais;
import panizio.utils.ManipularCampos;

/**
 *
 * @author lucas Panizio
 */
public class FormOcorrencia extends javax.swing.JFrame {

    private static TabelasDAO tblDAO = new TabelasDAO();

    /**
     * Creates new form FormOcorrencia
     */
    public FormOcorrencia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel1 = new javax.swing.JPanel();
        btnPesquisarOc = new javax.swing.JButton();
        txtPesquisarOc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblOcorrencias = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        cmbOcorrencias = new javax.swing.JComboBox<>();
        lblOcorrencias = new javax.swing.JLabel();
        lblNomeReceb = new javax.swing.JLabel();
        txtNomeReceb = new javax.swing.JTextField();
        btnSalvarOc = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtDescricaoOc = new javax.swing.JTextArea();
        lblCodOcorrencia = new javax.swing.JLabel();
        txtCodOcorrencia = new javax.swing.JTextField();
        btnIncluirOc = new javax.swing.JButton();
        btnCancelarOc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ocorrências");
        setResizable(false);

        JPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnPesquisarOc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panizio/imagens/zoom 20x20.png"))); // NOI18N
        btnPesquisarOc.setText("PESQUISAR");
        btnPesquisarOc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarOcActionPerformed(evt);
            }
        });
        btnPesquisarOc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPesquisarOcKeyPressed(evt);
            }
        });

        txtPesquisarOc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisarOcKeyPressed(evt);
            }
        });

        jLabel2.setText("Digite o número da Minuta para pesquisar suas ocorrências");

        javax.swing.GroupLayout JPanel1Layout = new javax.swing.GroupLayout(JPanel1);
        JPanel1.setLayout(JPanel1Layout);
        JPanel1Layout.setHorizontalGroup(
            JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(JPanel1Layout.createSequentialGroup()
                        .addComponent(txtPesquisarOc, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPesquisarOc))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPanel1Layout.setVerticalGroup(
            JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPesquisarOc)
                    .addComponent(txtPesquisarOc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tblOcorrencias.setAutoCreateRowSorter(true);
        tblOcorrencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ocorrência", "Data Ocorrência", "Usuário"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblOcorrencias);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cmbOcorrencias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "ENTREGA REALIZADA", "AVARIA", "CLIENTE AUSENTE", "RECUSA", "DEVOLUÇÃO", "EXTRAVIO", "OCORRENCIA FECHADA", "FALTA DE TEMPO", "OUTRAS OCORRENCIAS" }));
        cmbOcorrencias.setEnabled(false);
        cmbOcorrencias.setMinimumSize(new java.awt.Dimension(50, 24));
        cmbOcorrencias.setPreferredSize(new java.awt.Dimension(50, 24));
        cmbOcorrencias.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbOcorrenciasFocusLost(evt);
            }
        });

        lblOcorrencias.setText("Ocorrência");

        lblNomeReceb.setText("Nome do Recebedor");

        txtNomeReceb.setEnabled(false);
        txtNomeReceb.setNextFocusableComponent(txtDescricaoOc);

        btnSalvarOc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panizio/imagens/check 22x22.png"))); // NOI18N
        btnSalvarOc.setText("SALVAR");
        btnSalvarOc.setEnabled(false);
        btnSalvarOc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarOcActionPerformed(evt);
            }
        });
        btnSalvarOc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSalvarOcKeyPressed(evt);
            }
        });

        txtDescricaoOc.setColumns(20);
        txtDescricaoOc.setRows(5);
        txtDescricaoOc.setBorder(javax.swing.BorderFactory.createTitledBorder("Descrição"));
        txtDescricaoOc.setEnabled(false);
        txtDescricaoOc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDescricaoOcKeyPressed(evt);
            }
        });
        jScrollPane6.setViewportView(txtDescricaoOc);

        lblCodOcorrencia.setText("Cód. Ocorrência");

        txtCodOcorrencia.setEnabled(false);
        txtCodOcorrencia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodOcorrenciaFocusLost(evt);
            }
        });

        btnIncluirOc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panizio/imagens/add 27x27.png"))); // NOI18N
        btnIncluirOc.setText("INCLUIR");
        btnIncluirOc.setEnabled(false);
        btnIncluirOc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirOcActionPerformed(evt);
            }
        });

        btnCancelarOc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panizio/imagens/cancel 22x22 (2).png"))); // NOI18N
        btnCancelarOc.setText("CANCELAR");
        btnCancelarOc.setEnabled(false);
        btnCancelarOc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarOcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnIncluirOc, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelarOc, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvarOc, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lblNomeReceb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNomeReceb))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lblCodOcorrencia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCodOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblOcorrencias)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbOcorrencias, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarOc)
                    .addComponent(btnCancelarOc)
                    .addComponent(btnIncluirOc, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodOcorrencia)
                    .addComponent(txtCodOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOcorrencias)
                    .addComponent(cmbOcorrencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNomeReceb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeReceb))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator3)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(JPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addComponent(JPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarOcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarOcActionPerformed
        if (!btnCancelarOc.isEnabled()) {
            if (!txtPesquisarOc.getText().isEmpty()) {
                int id_minuta = Integer.parseInt(txtPesquisarOc.getText());
                
                //SE A CONSULTA NO BANCO RETORNOU UMA MINUTA
                if (new MinutaDAO().obter(id_minuta) != null) {

                    tblDAO.atualizarTblOcorrencias((DefaultTableModel) tblOcorrencias.getModel(), id_minuta);                        
                   // tblOcorrencias.setSelectionBackground(Color.DARK_GRAY);
                    //tblOcorrencias.setSelectionForeground(Color.WHITE);

                    txtPesquisarOc.requestFocus();

                    //SE A CONSULTA NÃO RETORNOU OCORRENCIAS
                    if (tblOcorrencias.getModel().getRowCount() == 0) {
                        int opcao = JOptionPane.showConfirmDialog(this, "A minuta pesquisada não possui ocorrências." + '\n'
                                + "Deseja incluir uma ocorrência?", "INCLUIR OCORRÊNCIA", JOptionPane.YES_NO_OPTION);

                        if (opcao == JOptionPane.YES_OPTION) {
                            ManipularCampos.habilitar_desabilitar(Arrays.asList(btnCancelarOc, btnSalvarOc, txtNomeReceb,
                                    txtDescricaoOc, txtCodOcorrencia, cmbOcorrencias), true);
                            txtCodOcorrencia.requestFocus();
                        } else {
                            txtPesquisarOc.requestFocus();
                        }
                    } else {
                        btnIncluirOc.setEnabled(true);
                    }
                } 
                //SE A CONSULTA NO BANCO NÃO RETORNOU QUALQUER MINUTA
                else {
                    JOptionPane.showMessageDialog(null, "A minuta pesquisada não existe.", "ATENÇÃO!", JOptionPane.WARNING_MESSAGE);
                    txtPesquisarOc.requestFocus();
                }
            }
        }
    }//GEN-LAST:event_btnPesquisarOcActionPerformed

    private void btnPesquisarOcKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnPesquisarOcKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnPesquisarOc.doClick();
        }
    }//GEN-LAST:event_btnPesquisarOcKeyPressed

    private void txtPesquisarOcKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarOcKeyPressed
        if (txtPesquisarOc.getText().length() < 2) {
            ((DefaultTableModel) tblOcorrencias.getModel()).setRowCount(0);
            btnIncluirOc.setEnabled(false);
        }
    }//GEN-LAST:event_txtPesquisarOcKeyPressed

    private void btnSalvarOcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarOcActionPerformed
        List<Component> camposValidar = Arrays.asList(txtNomeReceb, cmbOcorrencias);

        //SE TODOS OS CAMPOS OBRIGATÓRIOS FORAM PREENCHIDOS
        if (!ManipularCampos.camposVaziosGenerico(camposValidar)) {

            int id_minuta = Integer.parseInt(txtPesquisarOc.getText());
            Ocorrencia oc = new Ocorrencia(txtCodOcorrencia.getText(), txtDescricaoOc.getText(),
                    txtNomeReceb.getText(), AtributosGlobais.usuario.getId(), id_minuta);

            //SE A INSERÇÃO NO BANCO FOI BEM SUCEDIDA
            if (new OcorrenciaDAO().inserir(oc)) {
                tblDAO.atualizarTblOcorrencias((DefaultTableModel) tblOcorrencias.getModel(), id_minuta);
                btnCancelarOcActionPerformed(evt);
            }

        } //EXISTE AO MENOS UM CAMPO OBRIGATÓRIO NÃO PREENCHIDO
        else {
            JOptionPane.showMessageDialog(null, "Preencha corretamente os campos.", "ATENÇÃO!", JOptionPane.WARNING_MESSAGE);
            txtCodOcorrencia.requestFocus();
        }
    }//GEN-LAST:event_btnSalvarOcActionPerformed

    private void btnSalvarOcKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSalvarOcKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnSalvarOc.doClick();
        }
    }//GEN-LAST:event_btnSalvarOcKeyPressed

    private void txtDescricaoOcKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescricaoOcKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_TAB) {
            btnSalvarOc.requestFocus();
        }
    }//GEN-LAST:event_txtDescricaoOcKeyPressed

    private void btnIncluirOcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirOcActionPerformed
        //SE OCORRÊNCIA DE BAIXA AINDA NÃO FOI LANÇADA
        if (!tblOcorrencias.getValueAt(0, 0).equals("ENTREGA REALIZADA")) {
            ManipularCampos.habilitar_desabilitar(Arrays.asList(txtCodOcorrencia, txtDescricaoOc,
                    cmbOcorrencias, txtNomeReceb, btnSalvarOc, btnCancelarOc), true);
            btnIncluirOc.setEnabled(false);
            txtPesquisarOc.setEditable(false);

            txtCodOcorrencia.requestFocus();
        } //OCORRÊNCIA DE BAIXA JÁ FOI LANÇADA
        else {
            JOptionPane.showMessageDialog(null, "Inclusão não permitida!" + '\n'
                    + "A minuta já foi baixada.", "ATENÇÃO!", JOptionPane.WARNING_MESSAGE);
            txtPesquisarOc.requestFocus();
        }
    }//GEN-LAST:event_btnIncluirOcActionPerformed

    private void btnCancelarOcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarOcActionPerformed
        btnIncluirOc.setEnabled(true);
        txtPesquisarOc.setEditable(true);
        ManipularCampos.limparCampos(Arrays.asList(txtCodOcorrencia, txtDescricaoOc, txtNomeReceb));
        cmbOcorrencias.setSelectedIndex(0);
        ManipularCampos.habilitar_desabilitar(Arrays.asList(btnCancelarOc, btnSalvarOc,
                txtCodOcorrencia, txtNomeReceb, txtDescricaoOc, cmbOcorrencias), false);
    }//GEN-LAST:event_btnCancelarOcActionPerformed

    private void txtCodOcorrenciaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodOcorrenciaFocusLost
        String cod = txtCodOcorrencia.getText();
        if (Arrays.asList("01", "02", "03", "04", "05", "06", "07", "08", "09").contains(cod)) {
            cmbOcorrencias.setSelectedIndex(Integer.parseInt(cod));
        } else {
            JOptionPane.showMessageDialog(this, "Código inválido.", "ATENÇÃO!", JOptionPane.WARNING_MESSAGE);
            txtCodOcorrencia.setText(null);            
        }
    }//GEN-LAST:event_txtCodOcorrenciaFocusLost

    private void cmbOcorrenciasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbOcorrenciasFocusLost
        int cod = cmbOcorrencias.getSelectedIndex();
        if (cod != 0) {
            txtCodOcorrencia.setText("0" + String.valueOf(cod));
        }
    }//GEN-LAST:event_cmbOcorrenciasFocusLost


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormOcorrencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormOcorrencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormOcorrencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormOcorrencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormOcorrencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel1;
    private javax.swing.JButton btnCancelarOc;
    private javax.swing.JButton btnIncluirOc;
    private javax.swing.JButton btnPesquisarOc;
    private javax.swing.JButton btnSalvarOc;
    private javax.swing.JComboBox<String> cmbOcorrencias;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblCodOcorrencia;
    private javax.swing.JLabel lblNomeReceb;
    private javax.swing.JLabel lblOcorrencias;
    private javax.swing.JTable tblOcorrencias;
    private javax.swing.JTextField txtCodOcorrencia;
    private javax.swing.JTextArea txtDescricaoOc;
    private javax.swing.JTextField txtNomeReceb;
    private javax.swing.JTextField txtPesquisarOc;
    // End of variables declaration//GEN-END:variables
}
